name: CICD2

services:
  nginx:
    build: .
    ports:
    - "8080:80"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
    - max_info

  prometheus:
    image: prom/prometheus:latest
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
    - max_info

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
    - "9113:9113"
    command:
    - --nginx.scrape-uri=http://nginx:80/stub_status
    networks:
    - max_info

networks:
  max_info:
    driver: bridge