global:
  scrape_interval: 15s # Scrape every 15 seconds (good for testing; adjust as needed).
  scrape_timeout: 10s # Default timeout for scrapes.

scrape_configs:
  # Scrape Prometheus itself (already running at localhost:9090, but inside Docker, it’s the service name).
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"] # Service name ‘prometheus’ in docker-compose.

  # Scrape the nginx-prometheus-exporter.
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-prometheus-exporter:9113"] # Service name from docker-compose.

  - name: Dump Prometheus logs on failure
    if: failure()
    run: docker logs $(docker ps -aqf "name=prometheus")
