name: CI

on:
  push:
    branches: [main, feature/CI]
  pull_request:
    branches: [main]

# Define permissions for the GITHUB_TOKEN
permissions:
  contents: read # Needed to read the repository files for linting
  statuses: write # Needed to report linting results to GitHub Checks API

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5-dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker compose build

      - name: Start services
        run: |
          docker compose up -d

      - name: Wait for services to be healthy
        run: |
          TIMEOUT=120
          INTERVAL=5
          ELAPSED=0
          while [ $ELAPSED -lt $TIMEOUT ]; do
            UNHEALTHY=$(docker ps --filter 'health=unhealthy' --format '{{.Names}}')
            HEALTHY_COUNT=$(docker ps --filter 'health=healthy' --format '{{.Names}}' | wc -l)
            TOTAL=$(docker compose ps -q | wc -l)
            if [ "$HEALTHY_COUNT" -eq "$TOTAL" ]; then
              echo "All services are healthy!"
              exit 0
            fi
            if [ -n "$UNHEALTHY" ]; then
              echo "Some services are unhealthy: $UNHEALTHY"
              docker ps
              exit 1
            fi
            sleep $INTERVAL
            ELAPSED=$((ELAPSED + INTERVAL))
          done
          echo "Timed out waiting for services to be healthy."
          docker ps
          exit 1

      - name: Check nginx is serving content
        run: |
          curl --fail http://localhost:8080 || (docker compose logs && exit 1)

      - name: Tear down
        if: always()
        run: |
          docker compose down
