name: CI

on:
  push:
    branches: [main, feature/CI]
  pull_request:
    branches: [main]

# Define permissions for the GITHUB_TOKEN
permissions:
  contents: read # Needed to read the repository files for linting
  statuses: write # Needed to report linting results to GitHub Checks API

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5-dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker compose build

      - name: Start services
        run: |
          docker compose up -d

      - name: Tear down
        if: always()
        run: |
          docker compose down

      - name: Force failure for testing
        run: exit 1
