name: Lint Codebase
on: [push]
permissions:
  contents: read  # Limit to read-only unless write is needed
  checks: write   # Allow writing to checks (e.g., for linting reports)
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: super-linter/super-linter@v7.3.0